
include:
  - local: default-runners.yml
  - local: gitlab-runners.yml
    rules:
      - if: ($CI_SERVER_HOST == "gitlab.com") && ($CI_PROJECT_NAMESPACE == "cunity")

stages:
  - build
  - test
  - results
  - release


.cunit-build-template-base:
  stage: build
  script:
    - mkdir build-${CI_JOB_NAME}
    - cd build-${CI_JOB_NAME}
    - cmake ..
    - cmake --build . -j2
    - ctest --output-on-failure    
    - ./Examples/CI/cicd-pass-plain
    - ./Examples/CI/cicd-pass-setupfuncs
    - python3 -m junit2htmlreport --summary-matrix Examples/CI/*-Results.xml
    - cpack -G TGZ CUnit
  artifacts:
    paths:
    - CUnit/CUnit/CUnitCI.h
    - build-*/cunit-*.tar.gz
    - build-*/cunit-*.deb
    - build-*/Examples/CI/*-Results.*
    - build-*/Tests/*.xml
    reports:
      junit:
      - build-*/Examples/CI/*-Results.xml
      - build-*/Tests/*-Results.xml


.cunit-build-template:
  extends:
    - .docker-linux-job
    - .cunit-build-template-base

apple:
  extends:
    - .macos-job
    - .cunit-build-template-base 

windows:
  stage: build
  tags:
    - saas-windows-medium-amd64
  script:
    - mkdir build-windows
    - cd build-windows
    - cmake .. 
    - cmake --build .
    - ctest -C Debug

ubuntu2004:
  extends:
    - .cunit-build-template
  image: ubuntu:20.04
  before_script:
    - apt-get update
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get install -y --no-install-recommends cmake build-essential make python3-pip
    - pip install junit2html

ubuntu2004-notests:
  extends:
    - ubuntu2004
  script:
    - mkdir build-${CI_JOB_NAME}
    - cd build-${CI_JOB_NAME}
    - cmake .. -DCUNIT_DISABLE_TESTS=TRUE -DCUNIT_DISABLE_EXAMPLES=TRUE
    - cmake --build . -j 2
    - find . -type f

alpine:
  extends:
    - .cunit-build-template
  image: alpine:3.14
  before_script:
    - apk update
    - apk add cmake gcc make libc-dev python3 py3-pip
    - pip3 install junit2html


alpine-dirbuild:
  stage: test
  needs:
    - alpine
  extends:
    - alpine
  script:
  - cd CMakeExamples/CMakeSubmodule
  - ln -s ../../. cunit-x.y.z
  - mkdir bld
  - cd bld
  - cmake ..
  - cmake --build .
  - ./test-program


alpine-pkgbuild:
  stage: test
  needs:
    - alpine
  extends:
    - alpine
  script:
    - find . -type f -name "*.tar.gz"
    - mkdir -p packages/cunit
    - tar -vxf build-alpine/cunit-3.*.tar.gz --strip-components=1 -C packages/cunit
    - cd CMakeExamples/CMakeFindPackage
    - mkdir bld
    - cd bld
    - cmake .. -DCUnit_DIR=$(pwd)/../../../packages/cunit/CUnit/share/cmake
    - cmake --build .
    - ./test-program

pages:
  stage: release
  image: alpine:3.14
  needs:
    - alpine
  script:
    - apk update
    - apk add doxygen
    - doxygen Doxyfile
    - mv doc/html/ public/
  artifacts:
    paths:
    - public
